services:
  # This reads settings from the extension UI and
  # has the code that listens to docker events and
  # manages containers.
  imds-proxy-controller:
    image: ${DESKTOP_PLUGIN_IMAGE}
    container_name: imds-proxy-controller
    network_mode: none
    volumes:
    # So we can have access to the host docker daemon:
    - /var/run/docker.sock:/var/run/docker.sock
    # To store persistent configuration:
    - imds-proxy-config:/data:rw
    # To communicate with the imds-proxy service:
    - imds-proxy-sockets:/var/run/imds-proxy:rw

  # Proxies IMDS requests from containers to the
  # extension's configured backend.
  imds-proxy:
    container_name: imds-proxy
    image: barnacle-imds-proxy-proxy:latest
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      # IPv4 + EC2 IPv6 IMDS addresses (AWS, GCP, OpenStack v4)
      imds_0:
        ipv4_address: 169.254.169.254
        ipv6_address: "fd00:ec2::254"
      # OpenStack IPv6 IMDS address
      imds_1:
        ipv6_address: "fd00:a9fe:a9fe::254"
    volumes:
      # So we can communicate with the controller
      - imds-proxy-sockets:/var/run/imds-proxy:rw
    # Try restarting up to 10 times on failure
    restart: on-failure:10

volumes:
  imds-proxy-config:
  imds-proxy-sockets:

networks:
  # Network 0: IPv4 IMDS (169.254.169.254) + EC2 IPv6 (fd00:ec2::254)
  imds_0:
    name: ".imds-0"
    driver: bridge
    enable_ipv6: true
    labels:
      imds-proxy.managed: "true"
      imds-proxy.providers: "AWS=v4,v6;GCP=v4,v6;OpenStack=v4"
    ipam:
      config:
        - subnet: 169.254.169.0/24
        - subnet: "fd00:ec2::/64"

  # Network 1: OpenStack IPv6 IMDS address (fd00:a9fe:a9fe::254)
  imds_1:
    name: ".imds-1"
    driver: bridge
    enable_ipv6: true
    labels:
      imds-proxy.managed: "true"
      imds-proxy.providers: "OpenStack=v6"
    ipam:
      config:
        - subnet: "fd00:a9fe:a9fe::/64"
