FROM golang:1.26-alpine@sha256:d4c4845f5d60c6a974c6000ce58ae079328d03ab7f721a0734277e69905473e5 AS builder
WORKDIR /proxy
COPY proxy/go.* ./
RUN --mount=type=cache,target=/go/pkg/mod \
    --mount=type=cache,target=/root/.cache/go-build \
    go mod download
COPY proxy/. ./
RUN --mount=type=cache,target=/go/pkg/mod \
    --mount=type=cache,target=/root/.cache/go-build \
    go build -trimpath -ldflags="-s -w" -o /bin/imds-proxy

FROM alpine
COPY --from=builder /bin/imds-proxy /imds-proxy
EXPOSE 80
CMD ["/imds-proxy"]
